### PR TITLE
Change how we handle user's directories

### LINKED ISSUE #16: Change default directory mechanism for OSX
[dirs](https://docs.rs/dirs/3.0.2/dirs/) use different mechanisms to retrieve the user's config directory and cache directory.

* the `XDG base directory` and the `XDG user directory` specifications on Linux,
* the `Known Folder` system on Windows, and
* the `Standard Directories` on OSX.

We must use the `XDG` specifications for both Linux and OSX. WIndows stay on the `Known Folder` system.

### LINKED ISSUE #26: Add a subcommand to print the configuration directory location
Something like `cargo temp config-dir` maybe?

### PR DESCRIPTION
**Pull request by yozhgoor**
closes #16, closes #26

We will now use XDG directories system for *nix and the Known Folder system on Windows.
When the directory is created, we will print where.

### CODE REVIEW

**Comment by YohDeadfall** [comment]
Is this change required? The description for `dirs` says:

> A tiny low-level library that provides platform-specific standard locations of directories for config, cache and other data on Linux, Windows, macOS and Redox **by leveraging the mechanisms defined by the XDG base/user directory specifications on Linux**, the Known Folder API on Windows, and the Standard Directory guidelines on macOS.

**Comment by yozhgoor** [comment]
Yes, its for OSX users who uses the XDG system instead of the Standard Directory guidelines
That (i think) won't impact others OS

**Comment by yozhgoor** [comment]
You can see more here: https://github.com/dirs-dev/directories-rs/issues/62
It's complicated :rocket:

**Comment by cecton** [comment]
> Is this change required? The description for `dirs` says:
> 
> > A tiny low-level library that provides platform-specific standard locations of directories for config, cache and other data on Linux, Windows, macOS and Redox **by leveraging the mechanisms defined by the XDG base/user directory specifications on Linux**, the Known Folder API on Windows, and the Standard Directory guidelines on macOS.

It's a question of CLI vs GUI for OSX

**Pull request merged**
